---

- name: set config file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: change permission access.log
  file:
    path: /var/log/nginx/access.log
    state: touch
    mode: 0644
  notify:
    - restart nginx

- name: change permission access.log's dir
  file:
    path: /var/log/nginx/
    state: directory
    mode: 0755
  notify:
    - restart nginx

- name: started nginx
  service:
    name: nginx
    state: started
