- hosts: all
  tasks:
    - name: download webapp
      synchronize:
        src: /home/isucon/webapp
        dest: ./
        mode: pull
    - name: download env.sh
      synchronize:
        src: /home/isucon/env.sh
        dest: ./env.sh
        mode: pull
