---

- name: set config file
  template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify:
    - restart mysql

- name: change permission slow.log
  file:
    path: /var/log/mysql/mysql-slow.log
    state: touch
    mode: 0666
  notify:
    - restart mysql

- name: change permission slow.log's dir
  file:
    path: /var/log/mysql/
    state: directory
    mode: 0755
  notify:
    - restart mysql

- name: started mysql
  service:
    name: mysql
    state: started
